<?xml version="1.0" encoding="utf-8"?><Database Class="DataBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="Assets">
    <Type Name="Asset">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" IsDelayLoaded="true" />
      <Column Name="Title" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="Payments">
    <Type Name="Payment">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" IsDelayLoaded="true" />
      <Column Name="Price" Type="System.Int32" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" CanBeNull="false" />
      <Column Name="IsCredit" Storage="_Type" Type="System.Boolean" CanBeNull="false" />
      <Column Name="IsCard" Type="System.Boolean" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="nvarchar(2000)" CanBeNull="false" />
      <Column Name="RentIdentity" Type="System.Int32" CanBeNull="false" />
      <Column Name="MemberId" Type="System.Int32" CanBeNull="false" />
      <Association Name="Payment_CardSerialPayment" Member="CardSerialPayments" ThisKey="ID" OtherKey="PaymentID" Type="CardSerialPayment" />
      <Association Name="Member_Payment" Member="Member" ThisKey="MemberId" OtherKey="ID" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="Teachers">
    <Type Name="Teacher">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" IsDelayLoaded="true" />
      <Column Name="FirstName" Type="System.String" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" CanBeNull="false" />
      <Column Name="PricePublic" Type="System.String" CanBeNull="false" />
      <Column Name="PricePrivate" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="Traninigs">
    <Type Name="Traninig">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" IsDelayLoaded="true" />
    </Type>
  </Table>
  <Table Name="" Member="Contests">
    <Type Name="Contest">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" IsDelayLoaded="true" />
      <Column Name="Title" Storage="_FirstName" Type="System.String" DbType="nvarchar(20)" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="Shifts">
    <Type Name="Shift">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" IsDelayLoaded="true" />
      <Column Name="Title" Type="System.String" CanBeNull="false" />
      <Column Name="Percent" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="Facilities">
    <Type Name="Facilities">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" IsDelayLoaded="true" />
      <Column Name="Title" Type="System.String" CanBeNull="false" />
      <Column Name="Price" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="Cabinets">
    <Type Name="Cabinet">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="nvarchar(30)" CanBeNull="false" />
      <Column Name="IsAvailable" Type="System.Boolean" CanBeNull="false" />
      <Association Name="Cabinet_MemberCabinet" Member="MemberCabinets" ThisKey="ID" OtherKey="CabinetID" Type="MemberCabinet" />
    </Type>
  </Table>
  <Table Name="" Member="Levels">
    <Type Name="Level">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="nvarchar(30)" CanBeNull="false" />
      <Association Name="Level_Member" Member="Members" ThisKey="ID" OtherKey="LevelID" Type="Member" />
    </Type>
  </Table>
  <Table Name="" Member="Teams">
    <Type Name="Team">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="nvarchar(30)" CanBeNull="false" />
      <Association Name="Team_TeamMember" Member="TeamMembers" ThisKey="ID" OtherKey="TeamID" Type="TeamMember" />
    </Type>
  </Table>
  <Table Name="" Member="PlayingBoardGroupTitles">
    <Type Name="PlayingBoardGroupTitle">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Member="GroupTitle" Storage="_Title" Type="System.String" DbType="nvarchar(30)" CanBeNull="false" />
      <Association Name="PlayingBoardGroupTitle_PlayingBoardTitle" Member="PlayingBoardTitles" ThisKey="ID" OtherKey="PlayingBoardGroupTitleID" Type="PlayingBoardTitle" />
    </Type>
  </Table>
  <Table Name="" Member="SocialNetworkTypes">
    <Type Name="SocialNetworkType">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="nvarchar(30)" CanBeNull="false" />
      <Association Name="SocialNetworkType_SocialNetworkAccount" Member="SocialNetworkAccounts" ThisKey="ID" OtherKey="SocialNetworkTypeID" Type="SocialNetworkAccount" />
    </Type>
  </Table>
  <Table Name="" Member="Phones">
    <Type Name="Phone">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="nvarchar(30)" CanBeNull="false" />
      <Association Name="Phone_PhoneNumber" Member="PhoneNumbers" ThisKey="ID" OtherKey="PhoneID" Type="PhoneNumber" />
    </Type>
  </Table>
  <Table Name="" Member="PlayingBoards">
    <Type Name="PlayingBoard">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Storage="_Title" Type="System.String" DbType="nvarchar(30)" CanBeNull="false" />
      <Column Name="IsAvailable" Type="System.Boolean" CanBeNull="false" />
      <Column Name="PlayingBoardTitleID" Type="System.Int32" CanBeNull="false" />
      <Association Name="PlayingBoard_PlayingBoardType" Member="PlayingBoardTypes" ThisKey="ID" OtherKey="PlayingBoardID" Type="PlayingBoardType" />
      <Association Name="PlayingBoard_RaspBerryPlayingBoard" Member="RaspberryPis" ThisKey="ID" OtherKey="PlayingBoardID" Type="RaspBerryPlayingBoard" Cardinality="One" />
      <Association Name="PlayingBoardTitle_PlayingBoard" Member="PlayingBoardTitle" ThisKey="PlayingBoardTitleID" OtherKey="ID" Type="PlayingBoardTitle" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="PlayingBoardTypes">
    <Type Name="PlayingBoardType">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Storage="_Title" Type="System.String" DbType="nvarchar(30)" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" CanBeNull="false" />
      <Column Name="PlayingBoardID" Type="System.Int32" CanBeNull="false" />
      <Association Name="PlayingBoardType_RentPlayingBoard" Member="RentPlayingBoards" ThisKey="ID" OtherKey="PlayingBoardTypeID" Type="RentPlayingBoard" />
      <Association Name="PlayingBoard_PlayingBoardType" Member="PlayingBoard" ThisKey="PlayingBoardID" OtherKey="ID" Type="PlayingBoard" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="RentPlayingBoards">
    <Type Name="RentPlayingBoard">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegisterDate" Storage="_Title" Type="System.DateTime" CanBeNull="false" />
      <Column Name="StartTime" Type="System.String" DbType="nvarchar(8)" CanBeNull="false" />
      <Column Name="EndTime" Type="System.String" DbType="nvarchar(8)" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" CanBeNull="false" />
      <Column Name="PlayingBoardTypeID" Storage="_PlayingBoardID" Type="System.Int32" CanBeNull="false" />
      <Association Name="RentPlayingBoard_MemberRentPlayingBoard" Member="MemberRentPlayingBoards" ThisKey="ID" OtherKey="RentPlayingBoardID" Type="MemberRentPlayingBoard" />
      <Association Name="PlayingBoardType_RentPlayingBoard" Member="PlayingBoardType" ThisKey="PlayingBoardTypeID" OtherKey="ID" Type="PlayingBoardType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="MemberRentPlayingBoards">
    <Type Name="MemberRentPlayingBoard">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="nvarchar(20)" CanBeNull="false" />
      <Column Name="RentPlayingBoardID" Type="System.Int32" CanBeNull="false" />
      <Column Name="MemberID" Type="System.Int32" CanBeNull="false" />
      <Association Name="RentPlayingBoard_MemberRentPlayingBoard" Member="RentPlayingBoard" ThisKey="RentPlayingBoardID" OtherKey="ID" Type="RentPlayingBoard" IsForeignKey="true" />
      <Association Name="Member_MemberRentPlayingBoard" Member="Member" ThisKey="MemberID" OtherKey="ID" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="TeamMembers">
    <Type Name="TeamMember">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" CanBeNull="false" />
      <Column Name="DateStart" Type="System.DateTime" CanBeNull="false" />
      <Column Name="DateEnd" Type="System.DateTime" CanBeNull="false" />
      <Column Name="MemberID" Type="System.Int32" CanBeNull="false" />
      <Column Name="TeamID" Type="System.Int32" CanBeNull="false" />
      <Association Name="Team_TeamMember" Member="Team" ThisKey="TeamID" OtherKey="ID" Type="Team" IsForeignKey="true" />
      <Association Name="Member_TeamMember" Member="Member" ThisKey="MemberID" OtherKey="ID" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="SocialNetworkAccounts">
    <Type Name="SocialNetworkAccount">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Account" Storage="_Title" Type="System.String" DbType="nvarchar(100)" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" CanBeNull="false" />
      <Column Name="SocialNetworkTypeID" Type="System.Int32" CanBeNull="false" />
      <Column Name="MemberID" Type="System.Int32" CanBeNull="false" />
      <Association Name="Member_SocialNetworkAccount" Member="Member" ThisKey="MemberID" OtherKey="ID" Type="Member" IsForeignKey="true" />
      <Association Name="SocialNetworkType_SocialNetworkAccount" Member="SocialNetworkType" ThisKey="SocialNetworkTypeID" OtherKey="ID" Type="SocialNetworkType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="PhoneNumbers">
    <Type Name="PhoneNumber">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Storage="_Title" Type="System.String" DbType="nvarchar(20)" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" CanBeNull="false" />
      <Column Name="PhoneID" Type="System.Int32" CanBeNull="false" />
      <Column Name="MemberID" Type="System.Int32" CanBeNull="false" />
      <Association Name="Phone_PhoneNumber" Member="Phone" ThisKey="PhoneID" OtherKey="ID" Type="Phone" IsForeignKey="true" />
      <Association Name="Member_PhoneNumber" Member="Member" ThisKey="MemberID" OtherKey="ID" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="Members">
    <Type Name="Member">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="nvarchar(15)" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="nvarchar(20)" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="nvarchar(50)" CanBeNull="false" />
      <Column Name="NationalCode" Type="System.String" DbType="nvarchar(12)" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="nvarchar(20)" CanBeNull="false" />
      <Column Name="Sex" Type="System.String" DbType="nvarchar(20)" CanBeNull="false" />
      <Column Name="Image" Type="System.Byte[]" DbType="varbinary(max)" CanBeNull="false" />
      <Column Name="LevelID" Type="System.Int32" CanBeNull="false" />
      <Association Name="Member_Payment" Member="Payments" ThisKey="ID" OtherKey="MemberId" Type="Payment" />
      <Association Name="Member_MemberRentPlayingBoard" Member="MemberRentPlayingBoards" ThisKey="ID" OtherKey="MemberID" Type="MemberRentPlayingBoard" />
      <Association Name="Member_TeamMember" Member="TeamMembers" ThisKey="ID" OtherKey="MemberID" Type="TeamMember" />
      <Association Name="Member_SocialNetworkAccount" Member="SocialNetworkAccounts" ThisKey="ID" OtherKey="MemberID" Type="SocialNetworkAccount" />
      <Association Name="Member_PhoneNumber" Member="PhoneNumbers" ThisKey="ID" OtherKey="MemberID" Type="PhoneNumber" />
      <Association Name="Member_MemberCabinet" Member="MemberCabinets" ThisKey="ID" OtherKey="MemberID" Type="MemberCabinet" />
      <Association Name="Level_Member" Member="Level" ThisKey="LevelID" OtherKey="ID" Type="Level" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="MemberCabinets">
    <Type Name="MemberCabinet">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DateStart" Type="System.DateTime" CanBeNull="false" />
      <Column Name="DateEnd" Type="System.DateTime" CanBeNull="false" />
      <Column Name="MemberID" Type="System.Int32" CanBeNull="false" />
      <Column Name="CabinetID" Storage="_TeamID" Type="System.Int32" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" CanBeNull="false" />
      <Association Name="Cabinet_MemberCabinet" Member="Cabinet" ThisKey="CabinetID" OtherKey="ID" Type="Cabinet" IsForeignKey="true" />
      <Association Name="Member_MemberCabinet" Member="Member" ThisKey="MemberID" OtherKey="ID" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="PlayingBoardTitles">
    <Type Name="PlayingBoardTitle">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="nvarchar(30)" CanBeNull="false" />
      <Column Name="PlayingBoardGroupTitleID" Storage="_PlayingBoardTitleID" Type="System.Int32" CanBeNull="false" />
      <Association Name="PlayingBoardTitle_PlayingBoard" Member="PlayingBoards" ThisKey="ID" OtherKey="PlayingBoardTitleID" Type="PlayingBoard" />
      <Association Name="PlayingBoardGroupTitle_PlayingBoardTitle" Member="PlayingBoardGroupTitle" ThisKey="PlayingBoardGroupTitleID" OtherKey="ID" Type="PlayingBoardGroupTitle" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="RaspBerryPlayingBoards">
    <Type Name="RaspBerryPlayingBoard">
      <Column Name="PlayingBoardID" Storage="_PlayingBoardTitleID" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RaspberryPinID" Storage="_Title" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="PlayingBoard_RaspBerryPlayingBoard" Member="PlayingBoard" ThisKey="PlayingBoardID" OtherKey="ID" Type="PlayingBoard" IsForeignKey="true" />
      <Association Name="RaspberryPin_RaspBerryPlayingBoard" Member="RaspberryPin" ThisKey="RaspberryPinID" OtherKey="ID" Type="RaspberryPin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="RaspberryPins">
    <Type Name="RaspberryPin">
      <Column Name="ID" Storage="_PlayingBoardTitleID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PinNumber" Storage="_Title" Type="System.String" DbType="nvarchar(3)" CanBeNull="false" />
      <Column Name="IsAvailable" Type="System.Boolean" CanBeNull="false" />
      <Association Name="RaspberryPin_RaspBerryPlayingBoard" Member="RaspBerryPlayingBoards" ThisKey="ID" OtherKey="RaspberryPinID" Type="RaspBerryPlayingBoard" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="" Member="Configurations">
    <Type Name="Configuration">
      <Column Name="ID" Storage="_PlayingBoardTitleID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RaspberryIPAddress" Storage="_Title" Type="System.String" DbType="nvarchar(15)" CanBeNull="false" />
      <Column Name="RaspberryPortNumber" Storage="_IsAvailable" Type="System.String" DbType="nvarchar(4)" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="CardSerialPayments">
    <Type Name="CardSerialPayment">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" IsDelayLoaded="true" />
      <Column Name="CardPaymentIdentity" Storage="_Price" Type="System.String" DbType="nvarchar(20)" CanBeNull="false" />
      <Column Name="CardNumber" Storage="_Date" Type="System.String" DbType="nvarchar(20)" CanBeNull="false" />
      <Column Name="AccountNumber" Storage="_Type" Type="System.String" DbType="nvarchar(20)" CanBeNull="false" />
      <Column Name="BankAccountID" Type="System.Int32" CanBeNull="false" />
      <Column Name="PaymentID" Storage="_MemberId" Type="System.Int32" CanBeNull="false" />
      <Association Name="Payment_CardSerialPayment" Member="Payment" ThisKey="PaymentID" OtherKey="ID" Type="Payment" IsForeignKey="true" />
      <Association Name="BankAccount_CardSerialPayment" Member="BankAccount" ThisKey="BankAccountID" OtherKey="ID" Type="BankAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="BankAccounts">
    <Type Name="BankAccount">
      <Column Name="ID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BankTitle" Type="System.String" DbType="nvarchar(50)" CanBeNull="false" />
      <Column Name="CardNumber" Storage="_Date" Type="System.String" DbType="nvarchar(20)" CanBeNull="false" />
      <Column Name="AccountNumber" Storage="_Type" Type="System.String" DbType="nvarchar(20)" CanBeNull="false" />
      <Association Name="BankAccount_CardSerialPayment" Member="CardSerialPayments" ThisKey="ID" OtherKey="BankAccountID" Type="CardSerialPayment" />
    </Type>
  </Table>
</Database>